app = "openai-api-service"
primary_region = "sin"  # Singapore region, you can change this

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  MONGODB_DB_NAME = "api_service_db"
  MONGODB_USER_COLLECTION = "users"
  BACKEND_API_BASE_URL = "https://api.devsdocode.com/v1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
